version: '3.8'
services:
  odoo:
    image: odoo:16.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - PGDATA=/var/lib/pgsql/data/pgdata name=value
      - HOST=postgres
      - USER=local
      - PASSWORD=local
    depends_on:
      - psql
    ports:
      - '8069:8069'
    volumes:
      - data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/extra-addons
  psql:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - PGDATA=/var/lib/pgsql/data/pgdata name=value
      - HOST=postgres
      - USER=local
      - PASSWORD=local
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/pgsql/data/pgdata

  flowise:
    image: flowiseai/flowise:2.1.2
    container_name: flowise
    ports:
      - "15542:3000"
    environment:
      - PORT=3000
      - DEBUG=true
    volumes:
      - ./flowise/.flowise:/root/.flowise
volumes:
  data:
  db:
