version: '3.8'

volumes:
  chunimai_data:

services:
  db:
    container_name: chunimai-database
    image: postgres:16-alpine
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=chunimai
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
    volumes:
      - chunimai_data:/var/lib/postgresql/data
