export const oatMilkMenus = [
  'Matcha Latte',
  'Premium Matcha Latte',
  'Twist Matcha Latte',
  'Clear Matcha',
  'Caramel Fresh Milk',
  'Pinky Milk',
  'Black Tea',
  'Thai Milk Tea',
  'Whipped Cheese Thai Tea',
  'Espresso',
  'Americano',
  'Latte',
  'Cappuccino',
  'Es-Yen',
  'Mocha',
]

export const jellyMenus = [
  'Orange Juice',
  'Lemon Thai Tea',
  'Honey Lemonade',
  'Red Lemon Soda',
  'Honey Yuzu Soda',
  'Breezy Rose',
  'Plum Lemon Soda',
  'Craft Cola',
  'Fruit Sunshine Tea',
  'Matcha Latte',
  'Orange Matcha',
  'Coconut Flower Matcha',
  'Premium Matcha Latte',
  'Twist Matcha Latte',
  'Clear Matcha',
  'Caramel Fresh Milk',
  'Pinky Milk',
  'Black Tea',
  'Cocoa',
  'Thai Milk Tea',
  'Assam Black Milk Tea',
  'Whipped Cheese Thai Tea',
  'Dirty',
  'Espresso',
  'Americano',
  'Latte',
  'Cappuccino',
  'Es-Yen',
  'Mocha',
  'Honey Americano',
  'Black Yuzu',
  'Orange Coffee',
  'Coconut Flower Americano',
]

export const bakeryMenus = [
  'Garlic Parsley',
  'Banana Nutella Toast',
  'Sandwich',
  'Toffy Cake',
  'Chocolate Chip Muffin',
  'Congee',
  'Instant Noodle Cup',
  'Original Cookie',
  'Larva Choc Cookie',
  'Brownies',
  'Donut',
  'Kanom Khai',
]
